/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

const HttpHeader = IDL.Record({ name: IDL.Text, value: IDL.Text });
const HttpResponse = IDL.Record({
  status: IDL.Nat,
  headers: IDL.Vec(HttpHeader),
  body: IDL.Vec(IDL.Nat8),
});
const TransformInput = IDL.Record({
  context: IDL.Vec(IDL.Nat8),
  response: HttpResponse,
});

export const idlService = IDL.Service({
  generateHashtags: IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  generateTopics: IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  getTrending: IDL.Func([IDL.Text], [IDL.Text], []),
  getSidebarContent: IDL.Func([], [IDL.Text], []),
  setGeminiApiKey: IDL.Func([IDL.Text], [], []),
  transform: IDL.Func([TransformInput], [HttpResponse], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HttpHeader = IDL.Record({ name: IDL.Text, value: IDL.Text });
  const HttpResponse = IDL.Record({
    status: IDL.Nat,
    headers: IDL.Vec(HttpHeader),
    body: IDL.Vec(IDL.Nat8),
  });
  const TransformInput = IDL.Record({
    context: IDL.Vec(IDL.Nat8),
    response: HttpResponse,
  });
  return IDL.Service({
    generateHashtags: IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    generateTopics: IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    getTrending: IDL.Func([IDL.Text], [IDL.Text], []),
    getSidebarContent: IDL.Func([], [IDL.Text], []),
    setGeminiApiKey: IDL.Func([IDL.Text], [], []),
    transform: IDL.Func([TransformInput], [HttpResponse], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
